### ISSUE TITLE
OSX build fails

### ISSUE THREAD

**Issue by Newsworthy** [anojht/synology-cloud-sync-decrypt-tool#12]
Error comes up as "Open Source Synology Cloud Sync Decryption Tool Error" when launching.

Console shows:

`Failed to copy signing info for 18496, responsible for file:///private/var/folders/89/1p_f6bt519x57tvz1zwnzmjr0000gn/T/AppTranslocation/E7A19622-E1D8-403E-9A58-9DC7ADF4A428/d/Open%20Source%20Synology%20Cloud%20Sync%20Decryption%20Tool.app/Contents/MacOS/Open%20Source%20Synology%20Cloud%20Sync%20Decryption%20Tool: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"`

**Comment by Newsworthy** [comment]
When you click terminate, a new item appears in the console:

`RBSStateCapture remove item called for untracked item 274-138-703 (target:executable<Open Source Synology Cloud Sync Decryption Tool(501)>)`

**Comment by Newsworthy** [comment]
Apologies, this is on MacOS Catalina

**Comment by Newsworthy** [comment]
Interesting note, I downloaded V7, and it appeared to get further, even asking permission for disk access. But then I got this:

<img width="1792" alt="Screenshot 2020-04-01 at 17 14 52" src="https://user-images.githubusercontent.com/4532455/78160849-718ac100-743c-11ea-8120-0113f4996058.png">

**Comment by anojht** [comment]
Remove the installmefirst app and follow the Mac installation instructions in the readme.

**Comment by anojht** [comment]
You can also try the following command inside the Terminal application in your Mac but replace the path to the path of the Synology app:

`sudo codesign -f -s - "/Applications/Sound Forge Pro.app/Contents/MacOS/Sound Forge Pro"`

**Comment by Newsworthy** [comment]
Thanks for this, that console command got V7 working, but V8 still crashes. I'll try this out and let you know. Thanks for the software. :)

**Comment by anojht** [comment]
Np, glad V7 worked at least. Any logs regarding crashes are very helpful for debugging. The application also creates a log file when running, you can find the location of them in the readme.

**Comment by Newsworthy** [comment]
I'm watching it work now, and your software has worked where the official Synology one failed. It kept crashing trying to decrypt 1.2TB of files from Backblaze on Windows, but yours is working on my Mac.

You might just have saved my files after my old laptop was stolen. Thank you again. :)

I'll check in again when it has finished.

**Comment by anojht** [comment]
Oh wow, just a heads up, V7 might have had a bug decrypting very large files. Your file is really large. This bug was fixed in V8, so if V7 fails please try V8 and I will try my best to help you!

**Comment by Newsworthy** [comment]
Thankfully it is a Time Machine backup .spaarsebundle file, so it's 1.2TB of 8.2Mb files . :)

**Comment by anojht** [comment]
Hope the decryption is going well, please let me know whether things worked out for you so I can close the issue.

**Comment by Newsworthy** [comment]
Hi there, version 7 has managed to decrypt everything, so thank you for that. Filesystem within is corrupted but at least I can see the data now.

However, version 8 still won't even load. Still getting the error on load.

**Comment by anojht** [comment]
You can try the following for corrupted time machine backup: [Repairing Corrupted Time Machine Backups Synology](http://thefunkstop.com/fix-corrupted-time-machine-backups/)

Can you send me  a screenshot or attach application logs of the error you speak of with V8? It is not clear to me which error, since there are multiple in this thread.

**Comment by Newsworthy** [comment]
Hey Anojh, here is the transcript from the console under "errors" when I
try and launch version 8.

"Failed to copy signing info for 769, responsible for
file:///private/var/folders/89/1p_f6bt519x57tvz1zwnzmjr0000gn/T/AppTranslocation/BC3E0DFF-7140-4F40-875A-F2C6A5D93AC5/d/Open%20Source%20Synology%20Cloud%20Sync%20Decryption%20Tool.app/Contents/MacOS/Open%20Source%20Synology%20Cloud%20Sync%20Decryption%20Tool:
#-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)""

**Comment by Newsworthy** [comment]
Also thank you for that link, but sadly it didn't work in my situation.

**Comment by anojht** [comment]
Thanks for the error description, I have released a new compiled version of the app for MacOS after discovering and fixing a minor compile bug, can you try it out?

Under releases, download osx.zip file in V8 version. If you encounter the error message above try (replacing the path to the synology app):

`sudo codesign -f -s - "/Applications/Sound Forge Pro.app/Contents/MacOS/Sound Forge Pro"`

**Comment by Newsworthy** [comment]
Sorry for the delay, I was waiting on another drive to decrypt to, to
become free.

Just downloaded the new version, AND IT WORKS! Thanks for your help. :)

**Comment by anojht** [comment]
Great, thanks for pointing out the bug, I will close this issue as the problems are resolved.
